version: "3.8"

services:
    auth_service:
        image: auth_service
        container_name: auth_service
        build:
            context: .
            dockerfile: ./authentication_service/Dockerfile
        restart: on-failure
        environment:
            AUTH_SERVICE_PORT: ${AUTHENTICATION_SERVICE_PORT}
            MONGO_DB_HOST: ${AUTHENTICATION_MONGO_DB_HOST_DOCKER}
            MONGO_DB_PORT: ${MONGO_DB_PORT}      
            USER_SERVICE_HOST: ${USER_SERVICE_HOST_DOCKER}
            USER_SERVICE_PORT: ${USER_SERVICE_PORT}
            GATEWAY_HOST: ${GATEWAY_HOST_DOCKER}
            GATEWAY_PORT: ${GATEWAY_PORT}
        depends_on:
          - auth_mongo_db
        networks:
          - network

    user_service:
        image: user_service
        container_name: user_service
        build:
            context: .
            dockerfile: ./user_service/Dockerfile
        restart: on-failure
        environment:
            USER_SERVICE_PORT: ${USER_SERVICE_PORT}
            MONGO_DB_HOST: ${USER_MONGO_DB_HOST_DOCKER}
            MONGO_DB_PORT: ${MONGO_DB_PORT}
        depends_on:
            - user_mongo_db
        networks:
            - network
      
    post_service:
        image: post_service
        container_name: post_service
        build:
            context: .
            dockerfile: ./post_service/Dockerfile
        restart: on-failure
        environment:
            POST_SERVICE_PORT: ${POST_SERVICE_PORT}
            MONGO_DB_HOST: ${POST_MONGO_DB_HOST_DOCKER}
            MONGO_DB_PORT: ${MONGO_DB_PORT}
        depends_on:
            - post_mongo_db
        networks:
            - network

    api_gateway:
        image: api_gateway
        container_name: api_gateway
        build:
            context: .
            dockerfile: ./api_gateway/Dockerfile
        restart: on-failure
        ports:
            - ${GATEWAY_PORT}:${GATEWAY_PORT}
        environment:
            GATEWAY_PORT: ${GATEWAY_PORT}
            POST_SERVICE_HOST: ${POST_SERVICE_HOST_DOCKER}
            POST_SERVICE_PORT: ${POST_SERVICE_PORT}
            USER_SERVICE_HOST: ${USER_SERVICE_HOST_DOCKER}
            USER_SERVICE_PORT: ${USER_SERVICE_PORT}
            AUTH_SERVICE_HOST: ${AUTHENTICATION_SERVICE_HOST_DOCKER}
            AUTH_SERVICE_PORT: ${AUTHENTICATION_SERVICE_PORT}
        networks:
            - network

    auth_mongo_db:
        image: mongo
        container_name: auth_mongo_db
        command: mongod --quiet --logpath /dev/null
        restart: on-failure
        networks:
            - network
        logging:
            driver: none


    user_mongo_db:
        image: mongo
        container_name: user_mongo_db
        command: mongod --quiet --logpath /dev/null
        restart: on-failure
        networks:
            - network
        logging:
            driver: none

    post_mongo_db:
        image: mongo
        container_name: post_mongo_db
        command: mongod --quiet --logpath /dev/null
        restart: on-failure
        networks:
            - network
        logging:
            driver: none

networks:
    network:
        driver: bridge